services:
  - type: web
    name: trading-bot-websocket
    env: python
    plan: free

    buildCommand: >
      pip install --upgrade pip &&
      pip install -r requirements.txt

    startCommand: >
      gunicorn --worker-class eventlet -w 1 app:app

    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.8
